import React, {Component} from "react";
import {Text, View , StyleSheet ,Image,  ScrollView , Dimensions , ImageBackground } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";


const image = require('../../assets/Mask.png');
const logoImage2 = require('../../assets/Group-250.png');
const image2 = require('../../assets/Group-259.png');


class PrivacyPolicy extends Component{
  render() {
    return(

      <ImageBackground source={image} style={styles.image}>
      
      <ImageBackground source={image2} style={styles.image2} >
      <Image source={logoImage2} style={styles.image3} />
          <View style={styles.container} >
          
          <ScrollView style={styles.scrollViewStyle}>   
              <View style={styles.containerx} >
                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Privacy Policy</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>Effective date: June 30, 2019</Text>
                          <Text style={styles.SubHeadingText}>Gt Road FM ("us", "we", or "our") operates the Gt Road FM mobile application (hereinafter referred to as the "Service").</Text>
                          <Text style={styles.SubHeadingText}>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</Text>
                          <Text style={styles.SubHeadingText}>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</Text>

                      </View>
                      <View style={styles.container2}>
                          <Text style={styles.HeadingText}>Definitions</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingTextBold}>Service</Text>
                          <Text style={styles.SubHeadingText}>Service is the Gt Road FM mobile application operated by Gt Road FM</Text>
                          <Text style={styles.SubHeadingTextBold}>Personal Data</Text>
                          <Text style={styles.SubHeadingText}>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</Text>
                          <Text style={styles.SubHeadingTextBold}>Usage Data</Text>
                          <Text style={styles.SubHeadingText}>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
                          <Text style={styles.SubHeadingTextBold}>Usage Data</Text>
                          <Text style={styles.SubHeadingText}>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
                          <Text style={styles.SubHeadingTextBold}>Cookies</Text>
                          <Text style={styles.SubHeadingText}>Cookies are small files stored on your device (computer or mobile device).</Text>
                          <Text style={styles.SubHeadingTextBold}>Data Controller</Text>
                          <Text style={styles.SubHeadingText}>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</Text>
                          <Text style={styles.SubHeadingTextBold}>Data Processors (or Service Providers)</Text>
                          <Text style={styles.SubHeadingText}>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.We may use the services of various Service Providers in order to process your data more effectively.</Text>
                          <Text style={styles.SubHeadingTextBold}>Data Subject (or User)</Text>
                          <Text style={styles.SubHeadingText}>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</Text>

                      </View>
                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Information Collection</Text>
                          <Text style={styles.HeadingText} >and Use</Text>
                      </View>
                      <View style={styles.container3} >
                            <Text style={styles.SubHeadingText}>We collect several different types of information for various purposes to provide and improve our Service to you.</Text>
                      </View>
                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Types of Data Collected</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingTextBold}>Personal Data</Text>
                          <Text style={styles.SubHeadingText}>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: </Text>
                          <Text style={styles.SubHeadingTextBold}>Email address, First name and last name</Text>
                          <Text style={styles.SubHeadingTextBold}>Phone number,</Text>
                          <Text style={styles.SubHeadingTextBold}>Address, State, Province, ZIP/Postal code, City,</Text>
                          <Text style={styles.SubHeadingTextBold}>Cookies and Usage Data,</Text>
                          <Text style={styles.SubHeadingText}>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</Text>
                          <Text style={styles.SubHeadingTextBold}>Usage Data</Text>
                          <Text style={styles.SubHeadingText}>When you access the Service with a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data ("Usage Data").</Text>
                          <Text style={styles.SubHeadingTextBold}>Tracking & Cookies Data</Text>
                          <Text style={styles.SubHeadingText}>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. Examples of Cookies we use:</Text>
                          <Text style={styles.SubHeadingText}>Session Cookies. We use Session Cookies to operate our Service.
                          Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
                          Security Cookies. We use Security Cookies for security purposes.</Text>
      
                      </View>

                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Use of Data</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>Gt Road FM uses the collected data for various purposes:</Text>
                          <Text style={styles.SubHeadingText}>To provide and maintain our Service</Text>
                          <Text style={styles.SubHeadingText}>To notify you about changes to our Service</Text>
                          <Text style={styles.SubHeadingText}>To allow you to participate in interactive features of our Service when you agreement_for to do so</Text>
                          <Text style={styles.SubHeadingText}>To provide customer support</Text>
                          <Text style={styles.SubHeadingText}>To gather analysis or valuable information so that we can improve our Service</Text>
                          <Text style={styles.SubHeadingText}>To monitor the usage of our Service</Text>
                          <Text style={styles.SubHeadingText}>To detect, prevent and address technical issues</Text>
                          <Text style={styles.SubHeadingText}>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</Text>

                          </View>
                          <View style={styles.container3} > 
                          <Text style={styles.SubHeadingTextBold}>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</Text>
                          <Text style={styles.SubHeadingText}>If you are from the European Economic Area (EEA), Gt Road FM legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it. Gt Road FM may process your Personal Data because:</Text>
                          <Text style={styles.SubHeadingText}>We need to perform a contract with you</Text>
                          <Text style={styles.SubHeadingText}>You have given us permission to do so</Text>
                          <Text style={styles.SubHeadingText}>The processing is in our legitimate interests and it is not overridden by your rights</Text>
                          <Text style={styles.SubHeadingText}>For payment processing purposes</Text>
                          <Text style={styles.SubHeadingText}>To comply with the law</Text>

                          <Text style={styles.SubHeadingTextBold}>Retention of Data</Text>
                          <Text style={styles.SubHeadingText}>Gt Road FM will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies. Gt Road FM will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</Text>
                          <Text style={styles.SubHeadingTextBold}>Transfer of Data</Text>
                          <Text style={styles.SubHeadingText}>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside and choose to provide information to us, please note that we transfer the data, including Personal Data, to and process it there.Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.Gt Road FM will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</Text>
                          
                                                    
                      </View>
                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Disclosure of Data</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingTextBold}>Disclosure for Law Enforcement</Text>
                          <Text style={styles.SubHeadingText}>Under certain circumstances, Gt Road FM may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</Text>
                          <Text style={styles.SubHeadingTextBold}>Legal Requirements</Text>
                          <Text style={styles.SubHeadingText}>Gt Road FM may disclose your Personal Data in the good faith belief that such action is necessary to:</Text>
                          <Text style={styles.SubHeadingText}>To comply with a legal obligation</Text>
                          <Text style={styles.SubHeadingText}>To protect and defend the rights or property of Gt Road FM</Text>
                          <Text style={styles.SubHeadingText}>To prevent or investigate possible wrongdoing in connection with the Service</Text>
                          <Text style={styles.SubHeadingText}>To protect the personal safety of users of the Service or the public</Text>
                          <Text style={styles.SubHeadingText}>To protect against legal liability</Text>

                        </View>

                        <View style={styles.container3} > 
                          <Text style={styles.SubHeadingTextBold}>To protect against legal liability</Text>
                          <Text style={styles.SubHeadingText}>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</Text>
                          <Text style={styles.SubHeadingTextBold}>Our Policy on "Do Not Track" Signals under the California Online Protection Act (CalOPPA)</Text>
                          <Text style={styles.SubHeadingText}>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked. You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</Text>
                          <Text style={styles.SubHeadingTextBold}>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</Text>
                          <Text style={styles.SubHeadingText}>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Gt Road FM aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.
                          If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
                          In certain circumstances, you have the following data protection rights:
                          </Text>
                          
                          <Text style={styles.SubHeadingText}>The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</Text>

                          <Text style={styles.SubHeadingText}>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</Text>
                          <Text style={styles.SubHeadingText}>The right to object. You have the right to object to our processing of your Personal Data.</Text>
                          <Text style={styles.SubHeadingText}>The right of restriction. You have the right to request that we restrict the processing of your personal information.</Text>
                          <Text style={styles.SubHeadingText}>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</Text>
                          <Text style={styles.SubHeadingText}>The right to withdraw consent. You also have the right to withdraw your consent at any time where Gt Road FM relied on your consent to process your personal information.</Text>
                          <Text style={styles.SubHeadingText}>Please note that we may ask you to verify your identity before responding to such requests. You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</Text>
                      </View>

                      <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Service Providers</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</Text>
                          <Text style={styles.SubHeadingText}>Analytics</Text>
                          <Text style={styles.SubHeadingTextBold}>Google Analytics</Text>
                          <Text style={styles.SubHeadingText}>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.
You may opt-out of certain Google Analytics features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy
For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy
</Text>
                          <Text style={styles.SubHeadingTextBold}>Firebase</Text>
                          <Text style={styles.SubHeadingText}>Firebase is an analytics service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: https://policies.google.com/privacy We also encourage you to review the Google's policy for safeguarding your data: https://support.google.com/analytics/answer/6004245 For more information on what type of information Firebase collects, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy</Text>
                        </View>

                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Payments</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
The payment processors we work with are:
                          </Text>
                          {/* <Text style={styles.SubHeadingText}>Under certain circumstances, Gt Road FM may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</Text> */}
                          <Text style={styles.SubHeadingTextBold}>Apple Store In-App Payments</Text>
                          <Text style={styles.SubHeadingText}>Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en-ww/</Text>
                          <Text style={styles.SubHeadingTextBold}>Google Play In-App Payments</Text>
                          <Text style={styles.SubHeadingText}>Their Privacy Policy can be viewed at https://policies.google.com/privacy</Text>
                          

                        </View>

                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Links to Other Sites</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Text>
                          
                        </View>

                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Links to Other Sites</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Text>
                          
                        </View>

                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Children's Privacy</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>Our Service does not address anyone under the age of 18 ("Children").
We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                          </Text>
                          
                        </View>
                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Changes to This Privacy Policy</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                          </Text>
                          
                        </View>

                        <View style={styles.container2} >
                          <Text style={styles.HeadingText} >Contact Us</Text>
                      </View>
                      <View style={styles.container3} > 
                          <Text style={styles.SubHeadingText}>If you have any questions about this Privacy Policy, please contact us:</Text>
                          <Text style={styles.SubHeadingText}>By email: info@gtroadfm.com</Text>
                          <Text style={styles.SubHeadingText}>By visiting this page on our website: https://www.gtroadfm.com/contact-us</Text>
                          <Text style={styles.SubHeadingText}>By phone number: 416-615-2222</Text>
                        </View>





              </View>
      </ScrollView>
        </View>
    </ImageBackground>
  </ImageBackground>







    )
   }
  
};



const styles = StyleSheet.create({
    containerx: {
      // flex:1,
      // alignContent:"center",
      // alignItems:"center"
    },
      container: {
        flex: 1,
        width: "100%",
        // justifyContent: "center",
        paddingTop: 20,
        maxHeight: (Dimensions.get("window").height * .706) -150,
      },
      container2:{  
        // paddingTop:50,
        // paddingBottom:40
          // borderBottomWidth: StyleSheet.hairlineWidth,
          // borderTopWidth: 0,
          // borderBottomColor: "rgba(158, 150, 150, .5);",
          // borderTopColor: "rgba(158, 150, 150, .5);",
          // paddingLeft:"5%",
          // marginBottom:"5%"
      },
      HeadingText:{
        fontSize: RFValue(24),
        color: "white",
        fontWeight: "600"
      },
      SubHeadingText:{
          fontSize:RFValue(15),
          color: "white",
          textAlign: "justify",
          // alignSelf:"center"
          // paddingTop:"7%",
          // paddingBottom:"3%"
      },
      SubHeadingTextBold:{
        fontSize:RFValue(15),
        color: "white",
        // alignSelf:"center",
        fontWeight: "700",
        
        textAlign: "justify",
      },
      container3:{  
       // padding:10
          // borderBottomWidth: StyleSheet.hairlineWidth,
          // borderTopWidth: 0,
          // borderBottomColor: "rgba(158, 150, 150, .5);",
          // borderTopColor: "rgba(158, 150, 150, .5);",
          // paddingLeft:"5%"
      },
      image: {
        flex: 1,
        // resizeMode: "center",
        justifyContent: "center",
        
        // resizeMethod: "resize",
      },
      image2: {
        flex: 1,
        resizeMode: "center",
        justifyContent: "center",
        // resizeMethod: "resize",
        marginTop: 80,
        height : Dimensions.get("window").height * .806,
        width : Dimensions.get("window").width * 0.9,
        // alignContent:"center",
        alignSelf:"center"
      },
      image3: {
        resizeMode: "contain",
        height : 150,
        width : 150,
        marginTop: -200,
        // alignContent:"center",
        alignSelf:"center"
      },
      scrollViewStyle:{
        height:60,
        width : "100%",
        alignContent:"center",
        alignSelf:"center",
        paddingHorizontal:15,
        
      },
      images:{
          maxWidth:250,
          maxHeight:250,
          alignSelf:"center",
          resizeMode:"contain"
      },
      
    }
    );

export default PrivacyPolicy;